#!/usr/bin/env python3
"""
Hach Sales Action Alert - Immediate Opportunities
"""

import json
from datetime import datetime

def generate_action_alert():
    """Generate immediate action alert for sales team"""
    
    # Load the latest bid data
    try:
        with open('bid_data_20260303_192845.json', 'r', encoding='utf-8') as f:
            bid_data = json.load(f)
    except:
        return "No recent data available for action alert."
    
    if not bid_data:
        return "No opportunities found in latest scan."
    
    # Get the high-priority opportunity
    opportunity = bid_data[0]  # We know there's at least one high-priority
    
    alert = f"""
🚨 **IMMEDIATE HACH SALES ACTION REQUIRED**

📅 {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} GMT+8

## 🔥 HIGH PRIORITY OPPORTUNITY DETECTED

### **Project:** Water Quality Automated Monitoring Station O&M (2026-2027)

**🏢 Buyer Information:**
- Organization: {opportunity['source']}
- Contact Person: {opportunity.get('contact_info', {}).get('person', '陆瑶')}
- Phone: {opportunity.get('contact_info', {}).get('phone', '0523-86195822')}
- Address: {opportunity.get('contact_info', {}).get('address', '泰州市海陵南路309号')}
- Project Number: {opportunity.get('project_number', 'JSZC-321200-JSJW-G2025-0048')}

**⏰ Critical Dates:**
- Published: {opportunity.get('publication_date', '2025-07-10')}
- Deadline: {opportunity.get('deadline', '2025-07-31')} ⚠️ **DEADLINE APPROACHING**

**🎯 Hach Relevance:** {opportunity.get('relevance_score', 21)}/25 (PERFECT FIT)

**💼 Equipment Required:**
"""
    
    for req in opportunity.get('equipment_requirements', []):
        alert += f"- {req}\n"
    
    alert += f"""
**📋 Action Items for Hach Sales:**

1. **IMMEDIATE (Today):**
   - Contact 陆瑶 at 0523-86195822
   - Request detailed specifications and technical requirements
   - Ask about Hach prequalification requirements

2. **THIS WEEK:**
   - Prepare Hach product catalog relevant to automated monitoring
   - Review Hach's experience with similar O&M contracts
   - Identify key decision makers and influencers

3. **DEADLINE PREP:**
   - Submit Hach qualification documents
   - Prepare technical proposal for water quality monitoring systems
   - Schedule site visit if possible

**🔗 Project Link:** {opportunity.get('url', 'N/A')}

**📞 Recommended Approach:**
- Position Hach as the leader in water quality monitoring technology
- Emphasize Hach's experience with automated monitoring station O&M
- Highlight Hach's local support capabilities in Jiangsu Province

---
**⚡ This alert was generated by Hach Water Quality Bidding Monitor**
**Next scan scheduled for tomorrow at 9:00 AM**
"""
    
    return alert

if __name__ == "__main__":
    print(generate_action_alert())